SELECT
      ORDERKEY,
      PARTKEY ,
      SUPPLIERKEY,
      LINENUMBER,
      QUANTITY,
      EXTENDEDPRICE,
      DISCOUNT,
        TAX,
      RETURNFLAG,
      LINESTATUS,
      SHIPDATE,
      COMMITDATE,
      RECEIPTDATE,
      SHIPINSTRUCT,
      SHIPMODE,
      CUSTOMERKEY,
      ORDERSTATUS,
      TOTALPRICE,
      LINE_COMMENT,
      ORDERDATE,
      order_date_airflow,
      ORDERPRIORITY,
        CLERK,
      SHIPPRIORITY,
      ORDER_COMMENT,
        CUSTOMER_NAME,
      CUSTOMER_ADDRESS,
      CUSTOMER_NATION_KEY,
        CUSTOMER_PHONE,
      CUSTOMER_ACCBAL,
      CUSTOMER_MKTSEGMENT,
      CUSTOMER_COMMENT,
        CUSTOMER_NATION_NAME,
      CUSTOMER_REGION_KEY,
      CUSTOMER_NATION_COMMENT,
        CUSTOMER_REGION_NAME,
      CUSTOMER_REGION_COMMENT
FROM {{ source('tpch_sample_2', 'raw_orders') }}                
WHERE   
order_date_airflow >= DATEADD(day, -30, TO_DATE('{{ var('logical_date') }}'))
and order_date_airflow <= TO_DATE('{{ var('logical_date') }}')